# Generated by Django 4.2.1 on 2023-05-30 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='memories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('mapPlaceWeiht', models.FloatField()),
                ('mapPlaceLongitude', models.FloatField()),
                ('useruid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialapp')),
            ],
        ),
    ]
